version: "3.9"

services:
  api:
    build: .
    container_name: flask_api
    ports:
      - "6001:6001"   # map host port 5001 sang container
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres_db:5432/pythondb"
      REDIS_URL: "redis://redis-stack:6379/0"
      JWT_SECRET_KEY: "your_secret_key"
    networks:
      - flask-network

networks:
  flask-network:
    external: true
